"""add_base_url_and_http_headers_to_embedding_config

Revision ID: 89da9abca5b4
Revises: e8f64916f77c
Create Date: 2025-12-06 22:48:47.957475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '89da9abca5b4'
down_revision: Union[str, Sequence[str], None] = 'e8f64916f77c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_configs', sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('embedding_configs', sa.Column('http_headers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_configs', 'http_headers')
    op.drop_column('embedding_configs', 'base_url')
    # ### end Alembic commands ###
