"""add_base_url_and_http_headers_to_model_config

Revision ID: e8f64916f77c
Revises: 3a7c8d9e0f12
Create Date: 2025-12-06 22:26:09.983136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add this import

# revision identifiers, used by Alembic.
revision: str = 'e8f64916f77c'
down_revision: Union[str, Sequence[str], None] = '3a7c8d9e0f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embedding_configs', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('OPENROUTER', 'OLLAMA', 'OPENAI_COMPATIBLE', name='providertype'),
               existing_nullable=False)

    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('http_headers', sa.JSON(), nullable=True))
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('OPENROUTER', 'OLLAMA', 'OPENAI_COMPATIBLE', name='providertype'),
               existing_nullable=False)

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('OPENROUTER', 'OLLAMA', 'OPENAI_COMPATIBLE', name='providertype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.Enum('OPENROUTER', 'OLLAMA', 'OPENAI_COMPATIBLE', name='providertype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.Enum('OPENROUTER', 'OLLAMA', 'OPENAI_COMPATIBLE', name='providertype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('http_headers')
        batch_op.drop_column('base_url')

    with op.batch_alter_table('embedding_configs', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.Enum('OPENROUTER', 'OLLAMA', 'OPENAI_COMPATIBLE', name='providertype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
